os:
  - linux
language: node_js
before_install:
- sudo apt-get install build-essential libudev-dev -y
- sudo apt-get install libbluetooth-dev
install:
  - npm install
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8