os:
  - linux
  - osx
language: node_js
node_js:
  - "iojs"
  - "7"
install:
  - npm install
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8